# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1533, 899)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 561, 391))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.RGB_label = QtGui.QLabel(self.groupBox)
        self.RGB_label.setGeometry(QtCore.QRect(10, 20, 541, 361))
        self.RGB_label.setText(_fromUtf8(""))
        self.RGB_label.setObjectName(_fromUtf8("RGB_label"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 430, 561, 381))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Depth_label = QtGui.QLabel(self.groupBox_2)
        self.Depth_label.setGeometry(QtCore.QRect(50, 20, 461, 351))
        self.Depth_label.setText(_fromUtf8(""))
        self.Depth_label.setObjectName(_fromUtf8("Depth_label"))
        self.widget = QtGui.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(600, 20, 920, 790))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mainframe = QtGui.QFrame(self.widget)
        self.mainframe.setGeometry(QtCore.QRect(-1, 19, 911, 771))
        self.mainframe.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtGui.QFrame.Raised)
        self.mainframe.setObjectName(_fromUtf8("mainframe"))
        self.imu_settings_box = QtGui.QGroupBox(self.mainframe)
        self.imu_settings_box.setEnabled(False)
        self.imu_settings_box.setGeometry(QtCore.QRect(90, 390, 361, 381))
        self.imu_settings_box.setAutoFillBackground(False)
        self.imu_settings_box.setFlat(True)
        self.imu_settings_box.setCheckable(False)
        self.imu_settings_box.setObjectName(_fromUtf8("imu_settings_box"))
        self.default_config = QtGui.QCheckBox(self.imu_settings_box)
        self.default_config.setGeometry(QtCore.QRect(50, 20, 261, 17))
        self.default_config.setChecked(True)
        self.default_config.setObjectName(_fromUtf8("default_config"))
        self.frame_settings = QtGui.QFrame(self.imu_settings_box)
        self.frame_settings.setEnabled(False)
        self.frame_settings.setGeometry(QtCore.QRect(0, 40, 361, 341))
        self.frame_settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_settings.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_settings.setObjectName(_fromUtf8("frame_settings"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame_settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 281, 321))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.numIMUBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.numIMUBox.setMinimum(1)
        self.numIMUBox.setMaximum(2)
        self.numIMUBox.setObjectName(_fromUtf8("numIMUBox"))
        self.gridLayout.addWidget(self.numIMUBox, 0, 1, 1, 1)
        self.rate_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.rate_box.setObjectName(_fromUtf8("rate_box"))
        self.rate_box.addItem(_fromUtf8(""))
        self.rate_box.addItem(_fromUtf8(""))
        self.rate_box.addItem(_fromUtf8(""))
        self.rate_box.addItem(_fromUtf8(""))
        self.rate_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.rate_box, 5, 1, 1, 1)
        self.accel_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.accel_box.setObjectName(_fromUtf8("accel_box"))
        self.accel_box.addItem(_fromUtf8(""))
        self.accel_box.addItem(_fromUtf8(""))
        self.accel_box.addItem(_fromUtf8(""))
        self.accel_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.accel_box, 2, 1, 1, 1)
        self.gyro_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.gyro_box.setObjectName(_fromUtf8("gyro_box"))
        self.gyro_box.addItem(_fromUtf8(""))
        self.gyro_box.addItem(_fromUtf8(""))
        self.gyro_box.addItem(_fromUtf8(""))
        self.gyro_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.gyro_box, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.save_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.save_box.setObjectName(_fromUtf8("save_box"))
        self.save_box.addItem(_fromUtf8(""))
        self.save_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.save_box, 7, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.algo_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.algo_box.setObjectName(_fromUtf8("algo_box"))
        self.algo_box.addItem(_fromUtf8(""))
        self.algo_box.addItem(_fromUtf8(""))
        self.algo_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.algo_box, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 8, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.calib_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.calib_box.setObjectName(_fromUtf8("calib_box"))
        self.calib_box.addItem(_fromUtf8(""))
        self.calib_box.addItem(_fromUtf8(""))
        self.calib_box.addItem(_fromUtf8(""))
        self.calib_box.addItem(_fromUtf8(""))
        self.calib_box.setItemText(3, _fromUtf8(""))
        self.gridLayout.addWidget(self.calib_box, 6, 1, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 9, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.head_device_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.head_device_box.setEnabled(False)
        self.head_device_box.setObjectName(_fromUtf8("head_device_box"))
        self.head_device_box.addItem(_fromUtf8(""))
        self.head_device_box.addItem(_fromUtf8(""))
        self.head_device_box.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.head_device_box, 0, 1, 1, 1)
        self.shoulder_device_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.shoulder_device_box.setEnabled(False)
        self.shoulder_device_box.setObjectName(_fromUtf8("shoulder_device_box"))
        self.shoulder_device_box.addItem(_fromUtf8(""))
        self.shoulder_device_box.addItem(_fromUtf8(""))
        self.shoulder_device_box.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.shoulder_device_box, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.gridLayoutWidget.raise_()
        self.groupBox_4 = QtGui.QGroupBox(self.mainframe)
        self.groupBox_4.setGeometry(QtCore.QRect(550, 240, 361, 281))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 90, 281, 111))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.test_radio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.test_radio.setObjectName(_fromUtf8("test_radio"))
        self.gridLayout_2.addWidget(self.test_radio, 0, 0, 1, 1)
        self.save_radio = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.save_radio.setObjectName(_fromUtf8("save_radio"))
        self.gridLayout_2.addWidget(self.save_radio, 2, 0, 1, 1)
        self.start_btn = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.start_btn.setEnabled(False)
        self.start_btn.setCheckable(False)
        self.start_btn.setFlat(False)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.gridLayout_2.addWidget(self.start_btn, 1, 1, 1, 1)
        self.sensor_label = QtGui.QLabel(self.groupBox_4)
        self.sensor_label.setGeometry(QtCore.QRect(46, 220, 271, 20))
        self.sensor_label.setText(_fromUtf8(""))
        self.sensor_label.setObjectName(_fromUtf8("sensor_label"))
        self.acquisitions_sources = QtGui.QGroupBox(self.mainframe)
        self.acquisitions_sources.setGeometry(QtCore.QRect(90, 20, 361, 341))
        self.acquisitions_sources.setObjectName(_fromUtf8("acquisitions_sources"))
        self.verticalLayoutWidget = QtGui.QWidget(self.acquisitions_sources)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 321, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.kinect_radio = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kinect_radio.setAutoFillBackground(False)
        self.kinect_radio.setObjectName(_fromUtf8("kinect_radio"))
        self.verticalLayout.addWidget(self.kinect_radio)
        self.imu_radio = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.imu_radio.setObjectName(_fromUtf8("imu_radio"))
        self.verticalLayout.addWidget(self.imu_radio)
        self.kinect_imu_radio = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.kinect_imu_radio.setObjectName(_fromUtf8("kinect_imu_radio"))
        self.verticalLayout.addWidget(self.kinect_imu_radio)
        self.imu_settings_box.raise_()
        self.groupBox_4.raise_()
        self.acquisitions_sources.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 830, 101, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.labelFPS = QtGui.QLabel(self.horizontalLayoutWidget)
        self.labelFPS.setText(_fromUtf8(""))
        self.labelFPS.setObjectName(_fromUtf8("labelFPS"))
        self.horizontalLayout.addWidget(self.labelFPS)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(480, 830, 401, 31))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.calibBar = QtGui.QProgressBar(self.verticalLayoutWidget_2)
        self.calibBar.setProperty("value", 24)
        self.calibBar.setObjectName(_fromUtf8("calibBar"))
        self.verticalLayout_2.addWidget(self.calibBar)
        self.calibLabel = QtGui.QLabel(self.centralWidget)
        self.calibLabel.setGeometry(QtCore.QRect(900, 830, 221, 31))
        self.calibLabel.setObjectName(_fromUtf8("calibLabel"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1533, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuHome = QtGui.QMenu(self.menuBar)
        self.menuHome.setObjectName(_fromUtf8("menuHome"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionHome = QtGui.QAction(MainWindow)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.menuHome.addAction(self.actionHome)
        self.menuBar.addAction(self.menuHome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "RGB", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Depth", None))
        self.imu_settings_box.setTitle(_translate("MainWindow", "IMU Settings", None))
        self.default_config.setText(_translate("MainWindow", "Use default configuration", None))
        self.label_11.setText(_translate("MainWindow", "Number of devices", None))
        self.rate_box.setItemText(0, _translate("MainWindow", "100hz", None))
        self.rate_box.setItemText(1, _translate("MainWindow", "200hz", None))
        self.rate_box.setItemText(2, _translate("MainWindow", "50hz", None))
        self.rate_box.setItemText(3, _translate("MainWindow", "33hz", None))
        self.rate_box.setItemText(4, _translate("MainWindow", "25hz", None))
        self.accel_box.setItemText(0, _translate("MainWindow", "4g", None))
        self.accel_box.setItemText(1, _translate("MainWindow", "2g", None))
        self.accel_box.setItemText(2, _translate("MainWindow", "8g", None))
        self.accel_box.setItemText(3, _translate("MainWindow", "16g", None))
        self.gyro_box.setItemText(0, _translate("MainWindow", "500dps", None))
        self.gyro_box.setItemText(1, _translate("MainWindow", "250dps", None))
        self.gyro_box.setItemText(2, _translate("MainWindow", "1000dps", None))
        self.gyro_box.setItemText(3, _translate("MainWindow", "2000dps", None))
        self.label_4.setText(_translate("MainWindow", "Sample rate", None))
        self.save_box.setItemText(0, _translate("MainWindow", "False", None))
        self.save_box.setItemText(1, _translate("MainWindow", "True", None))
        self.label_7.setText(_translate("MainWindow", "Store configuration", None))
        self.label_2.setText(_translate("MainWindow", "Gyroscope", None))
        self.label.setText(_translate("MainWindow", "Accelerometer", None))
        self.label_3.setText(_translate("MainWindow", "Algorithm", None))
        self.algo_box.setItemText(0, _translate("MainWindow", "kalman", None))
        self.algo_box.setItemText(1, _translate("MainWindow", "compass", None))
        self.algo_box.setItemText(2, _translate("MainWindow", "gyro", None))
        self.label_6.setText(_translate("MainWindow", "Device", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "False", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "True", None))
        self.label_5.setText(_translate("MainWindow", "Calibration", None))
        self.label_8.setText(_translate("MainWindow", "Save calibration", None))
        self.label_9.setText(_translate("MainWindow", "Load Calibration", None))
        self.calib_box.setItemText(0, _translate("MainWindow", "None", None))
        self.calib_box.setItemText(1, _translate("MainWindow", "Auto", None))
        self.calib_box.setItemText(2, _translate("MainWindow", "Load", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "False", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "True", None))
        self.label_13.setText(_translate("MainWindow", "shoulder", None))
        self.head_device_box.setItemText(0, _translate("MainWindow", "COM7", "EXLs3-0239"))
        self.head_device_box.setItemText(1, _translate("MainWindow", "COM6", "EXLs3-0238"))
        self.head_device_box.setItemText(2, _translate("MainWindow", "COM3", None))
        self.shoulder_device_box.setItemText(0, _translate("MainWindow", "COM6", "EXLs3-0239"))
        self.shoulder_device_box.setItemText(1, _translate("MainWindow", "COM7", "EXLs3-0238"))
        self.shoulder_device_box.setItemText(2, _translate("MainWindow", "COM3", None))
        self.label_14.setText(_translate("MainWindow", "head", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Operation", None))
        self.test_radio.setText(_translate("MainWindow", "Test", None))
        self.save_radio.setText(_translate("MainWindow", "Save", None))
        self.start_btn.setText(_translate("MainWindow", "Start", None))
        self.acquisitions_sources.setTitle(_translate("MainWindow", "Acquisition Sources", None))
        self.kinect_radio.setText(_translate("MainWindow", "Kinect 2", None))
        self.imu_radio.setText(_translate("MainWindow", "EXLs3", None))
        self.kinect_imu_radio.setText(_translate("MainWindow", "Kinect 2 and IMU", None))
        self.label_10.setText(_translate("MainWindow", "FPS: ", None))
        self.calibLabel.setText(_translate("MainWindow", "Keep your head as still as possible!", None))
        self.menuHome.setTitle(_translate("MainWindow", "File", None))
        self.actionHome.setText(_translate("MainWindow", "Home", None))

